[package]
name = "cloudflare-worker"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
linked-info-application = { path = "../../crates/application" }
linked-info-contracts = { path = "../../crates/contracts" }
linked-info-domain = { path = "../../crates/domain" }
linked-info-storage-d1 = { path = "../../crates/storage-d1" }
worker = { version = "0.8", features = ["http", "axum", "d1"] }
worker-macros = { version = "0.8", features = ['http'] }
axum = { version = "0.8", default-features = false, features = ["json", "query"] }
serde.workspace = true
serde_json.workspace = true
tower-service = "0.3.3"
uuid.workspace = true
